os:
  - osx
osx_image: xcode7.3
language: objective-c
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./swiftlint.sh; fi
script:
  - xcodebuild clean build -project Aftermath.xcodeproj -scheme Aftermath-iOS -sdk iphonesimulator
  - xcodebuild test -project Aftermath.xcodeproj -scheme Aftermath-iOS -sdk iphonesimulator
  - xcodebuild clean build -project Aftermath.xcodeproj -scheme Aftermath-Mac -sdk macosx
  - xcodebuild test -project Aftermath.xcodeproj -scheme Aftermath-Mac -sdk macosx
notifications:
  email: false
